language: python
python:
  - 3.6

install:
  - pip install unittest2
  - chmod u+x start.sh
  - chmod u+x end.sh

before_script:
  - set -o errexit; source ./start.sh

script:
  - python test.py

after_script:
  - ./end.sh
  - ls
